- name: Configure DNS Settings in NetworkManager
  gather_facts: False
  hosts: all
  become: true
  vars:
    become_password: '{{ lookup("credentials", "matt") }}'
  tasks:

  - name: Add IPv4 DNS server addresses
    community.general.nmcli:
      conn_name: ens18
      type: ethernet
      dns4:
        - 192.168.7.234
        - 192.168.4.1
      state: present
    ansible_become_user: root
    ansible_become_password: '{{ become_password }}' 