- name: Configure DNS Settings in NetworkManager
  gather_facts: False
  hosts: all
  become: true
  tasks:

  - name: Add IPv4 DNS server addresses
    community.general.nmcli:
      conn_name: ens18
      type: ethernet
      dns4:
        - 192.168.7.234
        - 192.168.4.1
      state: present